### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by Destinia** [candy02058912/meizibaobao#1]
圖片的大小要調查手機是哪種尺寸

**Comment by Destinia** [comment]
https://i.imgur.com/5jlGDLt.jpg(1080 X 809)
![5jlgdlt](https://cloud.githubusercontent.com/assets/12761571/20999199/fa111a28-bd4d-11e6-8ce5-7c69722faf41.jpg)

**Comment by Destinia** [comment]
目前測試 iPhone只要推大於手機size的 width就可以

**Comment by candy02058912** [comment]
讚讚讚

**Comment by Destinia** [comment]
這個issue很值得收藏

**Comment by candy02058912** [comment]
少了我愛人
